// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"
#include<string.h>
#include "innotech_meter.h"
#include "innotech_config.h"
#include "api_bridge.h"
#include "innotech_wifi.h"
#include "innotech_factory.h"

static char input_buf[19] = {0};
static char output_buf[20] = {0};


static aliyun_triad_t triad_config_success;
void array_convert(void)
{
    uint8_t input_idx = 0;
    uint8_t output_idx = 0;
    for(int i = 0;i < 6;i++)
    {
        output_buf[output_idx++] = input_buf[input_idx++];
        output_buf[output_idx++] = input_buf[input_idx++];
        if(output_idx != 18)
        {
            output_buf[output_idx++] = '.';
        }
    }
    output_buf[output_idx] = '\0';
}

uint8_t adjust_aliyun_success(void)
{
    uint8_t success_flag = 0;
    memset(&triad_config_success, 0, sizeof(aliyun_triad_t));
    int flag_DN = innotech_triad_get(triad_config_success.devicename, "DeviceName");
    int flag_DS = innotech_triad_get(triad_config_success.devicesecret, "DeviceSecret");
    int flag_PK = innotech_triad_get(triad_config_success.productkey, "ProductKey");
    if(flag_DN && flag_DS && flag_PK)
    {
        success_flag = 1;
    }else
    {
        success_flag = 0;
    }
    return success_flag;
}
void factory_show_timer(void)
{
    //show power current voltage cosumption
    static uint8_t factory_tick = 0;
    static uint8_t success_flag_200 = 0;
    if(factory_tick < 35)
    {
        factory_tick ++;
    }
    char all_num[15];
    double current_value = innotech_current_get();
    static double voltage_value = 0;
    static double power_value = 0;  
    {
        voltage_value = innotech_voltage_get();
        power_value = innotech_power_get();
    }
    snprintf(all_num, 15 ,"%.2lf", voltage_value);
    lv_label_set_text(ui_Label105, all_num);

    snprintf(all_num, 15 , "%.2lf", power_value);
    lv_label_set_text(ui_Label104, all_num);

    double cosumption = (double)innotech_consumption_get();

    snprintf(all_num, 15 ,"%.2lf", current_value);
    lv_label_set_text(ui_Label106, all_num);

    snprintf(all_num, 15 ,"%.2lf", cosumption);
    lv_label_set_text(ui_Label107, all_num);

    //adjust aliyun success
    if(adjust_aliyun_success())
    {
        lv_label_set_text(ui_Label114, "三元组校验成功");
    }else
    {
        lv_label_set_text(ui_Label114, "三元组校验失败");
    }
    strncpy(input_buf, triad_config_success.devicename, sizeof(input_buf) - 1);
    //show mac
    array_convert();
    lv_label_set_text(ui_Label65,output_buf);

    
    //adjust 200w success   ui_Label115
    if(factory_tick == 25)
    {
        if(innotech_fix_flag_get() == 1)
        {
            lv_obj_set_x(ui_Label115, -147);
            lv_label_set_text(ui_Label115, "200W校准完成");
            success_flag_200 = 1;
        }else
        {
            lv_obj_set_x(ui_Label115, -147);
            lv_label_set_text(ui_Label115, "200W校准失败");
        }
    }

    if(factory_tick > 28)
    {
        if(innotech_fix_flag_get() == 1 && success_flag_200 == 1)
        {
            lv_label_set_text(ui_Label_success, "开始200W测试");
            lv_label_set_text(ui_Label_success, "200W测试成功");
        }
    }
    //adjust 400w overflow
}
void ui_Screen11_screen_init(void)
{
    ui_Screen11 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen11, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label96 = lv_label_create(ui_Screen11);
    lv_obj_set_width(ui_Label96, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label96, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label96, -177);
    lv_obj_set_y(ui_Label96, -212);
    lv_obj_set_align(ui_Label96, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label96, "产测模式");
    lv_obj_set_style_text_color(ui_Label96, lv_color_hex(0x1AE6E2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label96, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label96, &ui_font_cance, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label97 = lv_label_create(ui_Screen11);
    lv_obj_set_width(ui_Label97, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label97, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label97, -61);
    lv_obj_set_y(ui_Label97, -211);
    lv_obj_set_align(ui_Label97, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label97, "硬件:");
    lv_obj_set_style_text_color(ui_Label97, lv_color_hex(0x1AE6E2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label97, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label97, &ui_font_cance, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label100 = lv_label_create(ui_Screen11);
    lv_obj_set_width(ui_Label100, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label100, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label100, -176);
    lv_obj_set_y(ui_Label100, -151);
    lv_obj_set_align(ui_Label100, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label100, "功率(W)");
    lv_obj_set_style_text_color(ui_Label100, lv_color_hex(0x1AE6E2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label100, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label100, &ui_font_cance, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label101 = lv_label_create(ui_Screen11);
    lv_obj_set_width(ui_Label101, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label101, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label101, 73);
    lv_obj_set_y(ui_Label101, -152);
    lv_obj_set_align(ui_Label101, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label101, "电压(V)");
    lv_obj_set_style_text_color(ui_Label101, lv_color_hex(0x1AE6E2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label101, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label101, &ui_font_cance, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label102 = lv_label_create(ui_Screen11);
    lv_obj_set_width(ui_Label102, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label102, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label102, -178);
    lv_obj_set_y(ui_Label102, -71);
    lv_obj_set_align(ui_Label102, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label102, "电流(A)");
    lv_obj_set_style_text_color(ui_Label102, lv_color_hex(0x1AE6E2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label102, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label102, &ui_font_cance, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label103 = lv_label_create(ui_Screen11);
    lv_obj_set_width(ui_Label103, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label103, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label103, 89);
    lv_obj_set_y(ui_Label103, -70);
    lv_obj_set_align(ui_Label103, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label103, "电量(KWh)");
    lv_obj_set_style_text_color(ui_Label103, lv_color_hex(0x1AE6E2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label103, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label103, &ui_font_cance, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label104 = lv_label_create(ui_Screen11);
    lv_obj_set_width(ui_Label104, LV_SIZE_CONTENT);   /// 20
    lv_obj_set_height(ui_Label104, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label104, -184);
    lv_obj_set_y(ui_Label104, -111);
    lv_obj_set_align(ui_Label104, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label104, "0000");
    lv_obj_set_style_text_font(ui_Label104, &ui_font_B108, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label105 = lv_label_create(ui_Screen11);
    lv_obj_set_width(ui_Label105, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label105, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label105, 83);
    lv_obj_set_y(ui_Label105, -111);
    lv_obj_set_align(ui_Label105, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label105, "000.00");
    lv_obj_set_style_text_font(ui_Label105, &ui_font_B108, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label106 = lv_label_create(ui_Screen11);
    lv_obj_set_width(ui_Label106, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label106, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label106, -170);
    lv_obj_set_y(ui_Label106, -33);
    lv_obj_set_align(ui_Label106, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label106, "00.00");
    lv_obj_set_style_text_font(ui_Label106, &ui_font_B108, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label107 = lv_label_create(ui_Screen11);
    lv_obj_set_width(ui_Label107, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label107, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label107, 95);
    lv_obj_set_y(ui_Label107, -34);
    lv_obj_set_align(ui_Label107, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label107, "00000.0");
    lv_obj_set_style_text_font(ui_Label107, &ui_font_B108, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label109 = lv_label_create(ui_Screen11);
    lv_obj_set_width(ui_Label109, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label109, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label109, -198);
    lv_obj_set_y(ui_Label109, 24);
    lv_obj_set_align(ui_Label109, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label109, "版本:");
    lv_obj_set_style_text_color(ui_Label109, lv_color_hex(0x1AE6E2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label109, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label109, &ui_font_cance, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label49 = lv_label_create(ui_Screen11);
    lv_obj_set_width(ui_Label49, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label49, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label49, -73);
    lv_obj_set_y(ui_Label49, 24);
    lv_obj_set_align(ui_Label49, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label49, PT01_VERSION);
    lv_obj_set_style_text_color(ui_Label49, lv_color_hex(0x1AE6E2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label49, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label49, &ui_font_B108, LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_Label110 = lv_label_create(ui_Screen11);
    lv_obj_set_width(ui_Label110, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label110, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label110, -194);
    lv_obj_set_y(ui_Label110, 73);
    lv_obj_set_align(ui_Label110, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label110, "MAC:");
    lv_obj_set_style_text_color(ui_Label110, lv_color_hex(0x1AE6E2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label110, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label110, &ui_font_cance, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label65 = lv_label_create(ui_Screen11);
    lv_obj_set_width(ui_Label65, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label65, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label65, -25);
    lv_obj_set_y(ui_Label65, 73);
    lv_obj_set_align(ui_Label65, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label65, " ");
    lv_obj_set_style_text_color(ui_Label65, lv_color_hex(0x1AE6E2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label65, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label65, &ui_font_B108, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label114 = lv_label_create(ui_Screen11);
    lv_obj_set_width(ui_Label114, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label114, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label114, -147);
    lv_obj_set_y(ui_Label114, 111);
    lv_obj_set_align(ui_Label114, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label114, " ");
    lv_obj_set_style_text_color(ui_Label114, lv_color_hex(0x1AE6E2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label114, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label114, &ui_font_cance, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label115 = lv_label_create(ui_Screen11);
    lv_obj_set_width(ui_Label115, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label115, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label115, -144);
    lv_obj_set_y(ui_Label115, 144);
    lv_obj_set_align(ui_Label115, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label115, "开始200W校准");
    lv_obj_set_style_text_color(ui_Label115, lv_color_hex(0x1AE6E2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label115, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label115, &ui_font_cance, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label116 = lv_label_create(ui_Screen11);
    lv_obj_set_width(ui_Label116, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label116, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label116, -117);
    lv_obj_set_y(ui_Label116, 220);
    lv_obj_set_align(ui_Label116, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label116, "开始400W过载测试");
    lv_obj_set_style_text_color(ui_Label116, lv_color_hex(0x1AE6E2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label116, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label116, &ui_font_cance, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_success = lv_label_create(ui_Screen11);
    lv_obj_set_width(ui_Label_success, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_success, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_success, -148);
    lv_obj_set_y(ui_Label_success, 178);
    lv_obj_set_align(ui_Label_success, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_success, " ");
    lv_obj_set_style_text_color(ui_Label_success, lv_color_hex(0x1AE6E2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_success, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_success, &ui_font_cance, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Bar1 = lv_bar_create(ui_Screen11);
    lv_bar_set_value(ui_Bar1, 100, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar1, 483);
    lv_obj_set_height(ui_Bar1, 8);
    lv_obj_set_x(ui_Bar1, -7);
    lv_obj_set_y(ui_Bar1, -189);
    lv_obj_set_align(ui_Bar1, LV_ALIGN_CENTER);

    ui_Bar2 = lv_bar_create(ui_Screen11);
    lv_bar_set_value(ui_Bar2, 100, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar2, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar2, 490);
    lv_obj_set_height(ui_Bar2, 8);
    lv_obj_set_x(ui_Bar2, -5);
    lv_obj_set_y(ui_Bar2, -4);
    lv_obj_set_align(ui_Bar2, LV_ALIGN_CENTER);

    ui_Bar4 = lv_bar_create(ui_Screen11);
    lv_bar_set_value(ui_Bar4, 100, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar4, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar4, 490);
    lv_obj_set_height(ui_Bar4, 8);
    lv_obj_set_x(ui_Bar4, -2);
    lv_obj_set_y(ui_Bar4, 46);
    lv_obj_set_style_text_color(ui_Bar4, lv_color_hex(0x1AE6E2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_align(ui_Bar4, LV_ALIGN_CENTER);

    ui_Bar5 = lv_bar_create(ui_Screen11);
    lv_bar_set_value(ui_Bar5, 100, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar5, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar5, 490);
    lv_obj_set_height(ui_Bar5, 8);
    lv_obj_set_x(ui_Bar5, 6);
    lv_obj_set_y(ui_Bar5, 90);
    lv_obj_set_style_text_color(ui_Bar5, lv_color_hex(0x1AE6E2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_align(ui_Bar5, LV_ALIGN_CENTER);

    ui_Bar3 = lv_bar_create(ui_Screen11);
    lv_bar_set_value(ui_Bar3, 100, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar3, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar3, 4);
    lv_obj_set_height(ui_Bar3, 69);
    lv_obj_set_x(ui_Bar3, -117);
    lv_obj_set_y(ui_Bar3, -225);
    lv_obj_set_style_text_color(ui_Bar3, lv_color_hex(0x1AE6E2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_align(ui_Bar3, LV_ALIGN_CENTER);

    ui_Label47 = lv_label_create(ui_Screen11);
    lv_obj_set_width(ui_Label47, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label47, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label47, 6);
    lv_obj_set_y(ui_Label47, -212);
    lv_obj_set_align(ui_Label47, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label47, "V1.1");
    lv_obj_set_style_text_color(ui_Label47, lv_color_hex(0x1AE6E2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label47, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label47, &ui_font_cance, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_timer_create(factory_show_timer, 500, NULL);

}
