// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen7_screen_init(void)
{
    ui_Screen7 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label37 = lv_label_create(ui_Screen7);
    lv_obj_set_width(ui_Label37, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label37, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label37, -202);
    lv_obj_set_y(ui_Label37, -151);
    lv_obj_set_align(ui_Label37, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label37, "1");
    lv_obj_set_style_text_font(ui_Label37, &ui_font_B432, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label38 = lv_label_create(ui_Screen7);
    lv_obj_set_width(ui_Label38, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label38, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label38, -132);
    lv_obj_set_y(ui_Label38, -156);
    lv_obj_set_align(ui_Label38, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label38, "2");
    lv_obj_set_style_text_font(ui_Label38, &ui_font_B432, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label39 = lv_label_create(ui_Screen7);
    lv_obj_set_width(ui_Label39, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label39, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label39, -43);
    lv_obj_set_y(ui_Label39, -155);
    lv_obj_set_align(ui_Label39, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label39, "3");
    lv_obj_set_style_text_font(ui_Label39, &ui_font_B432, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label40 = lv_label_create(ui_Screen7);
    lv_obj_set_width(ui_Label40, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label40, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label40, 45);
    lv_obj_set_y(ui_Label40, -155);
    lv_obj_set_align(ui_Label40, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label40, "4");
    lv_obj_set_style_text_font(ui_Label40, &ui_font_B432, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label41 = lv_label_create(ui_Screen7);
    lv_obj_set_width(ui_Label41, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label41, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label41, 140);
    lv_obj_set_y(ui_Label41, -156);
    lv_obj_set_align(ui_Label41, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label41, "5");
    lv_obj_set_style_text_font(ui_Label41, &ui_font_B432, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label42 = lv_label_create(ui_Screen7);
    lv_obj_set_width(ui_Label42, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label42, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label42, -186);
    lv_obj_set_y(ui_Label42, 12);
    lv_obj_set_align(ui_Label42, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label42, "0");
    lv_obj_set_style_text_font(ui_Label42, &ui_font_B432, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label43 = lv_label_create(ui_Screen7);
    lv_obj_set_width(ui_Label43, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label43, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label43, -100);
    lv_obj_set_y(ui_Label43, 12);
    lv_obj_set_align(ui_Label43, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label43, "6");
    lv_obj_set_style_text_font(ui_Label43, &ui_font_B432, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label44 = lv_label_create(ui_Screen7);
    lv_obj_set_width(ui_Label44, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label44, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label44, -11);
    lv_obj_set_y(ui_Label44, 13);
    lv_obj_set_align(ui_Label44, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label44, "7");
    lv_obj_set_style_text_font(ui_Label44, &ui_font_B432, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label45 = lv_label_create(ui_Screen7);
    lv_obj_set_width(ui_Label45, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label45, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label45, 74);
    lv_obj_set_y(ui_Label45, 15);
    lv_obj_set_align(ui_Label45, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label45, "8");
    lv_obj_set_style_text_font(ui_Label45, &ui_font_B432, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label46 = lv_label_create(ui_Screen7);
    lv_obj_set_width(ui_Label46, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label46, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label46, 165);
    lv_obj_set_y(ui_Label46, 13);
    lv_obj_set_align(ui_Label46, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label46, "9");
    lv_obj_set_style_text_font(ui_Label46, &ui_font_B432, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label98 = lv_label_create(ui_Screen7);
    lv_obj_set_width(ui_Label98, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label98, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label98, -193);
    lv_obj_set_y(ui_Label98, 121);
    lv_obj_set_align(ui_Label98, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label98, "0");
    lv_obj_set_style_text_color(ui_Label98, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label98, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label98, &ui_font_B216, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label99 = lv_label_create(ui_Screen7);
    lv_obj_set_width(ui_Label99, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label99, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label99, -144);
    lv_obj_set_y(ui_Label99, 121);
    lv_obj_set_align(ui_Label99, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label99, "1");
    lv_obj_set_style_text_color(ui_Label99, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label99, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label99, &ui_font_B216, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label100 = lv_label_create(ui_Screen7);
    lv_obj_set_width(ui_Label100, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label100, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label100, -88);
    lv_obj_set_y(ui_Label100, 124);
    lv_obj_set_align(ui_Label100, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label100, "2");
    lv_obj_set_style_text_color(ui_Label100, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label100, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label100, &ui_font_B216, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label101 = lv_label_create(ui_Screen7);
    lv_obj_set_width(ui_Label101, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label101, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label101, -31);
    lv_obj_set_y(ui_Label101, 118);
    lv_obj_set_align(ui_Label101, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label101, "3");
    lv_obj_set_style_text_color(ui_Label101, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label101, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label101, &ui_font_B216, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label102 = lv_label_create(ui_Screen7);
    lv_obj_set_width(ui_Label102, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label102, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label102, 22);
    lv_obj_set_y(ui_Label102, 117);
    lv_obj_set_align(ui_Label102, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label102, "4");
    lv_obj_set_style_text_color(ui_Label102, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label102, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label102, &ui_font_B216, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label103 = lv_label_create(ui_Screen7);
    lv_obj_set_width(ui_Label103, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label103, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label103, 74);
    lv_obj_set_y(ui_Label103, 117);
    lv_obj_set_align(ui_Label103, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label103, "5");
    lv_obj_set_style_text_color(ui_Label103, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label103, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label103, &ui_font_B216, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label104 = lv_label_create(ui_Screen7);
    lv_obj_set_width(ui_Label104, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label104, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label104, 128);
    lv_obj_set_y(ui_Label104, 120);
    lv_obj_set_align(ui_Label104, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label104, "6");
    lv_obj_set_style_text_color(ui_Label104, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label104, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label104, &ui_font_B216, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label105 = lv_label_create(ui_Screen7);
    lv_obj_set_width(ui_Label105, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label105, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label105, 177);
    lv_obj_set_y(ui_Label105, 117);
    lv_obj_set_align(ui_Label105, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label105, "7");
    lv_obj_set_style_text_color(ui_Label105, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label105, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label105, &ui_font_B216, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label106 = lv_label_create(ui_Screen7);
    lv_obj_set_width(ui_Label106, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label106, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label106, -193);
    lv_obj_set_y(ui_Label106, 197);
    lv_obj_set_align(ui_Label106, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label106, "8");
    lv_obj_set_style_text_color(ui_Label106, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label106, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label106, &ui_font_B216, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label107 = lv_label_create(ui_Screen7);
    lv_obj_set_width(ui_Label107, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label107, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label107, -144);
    lv_obj_set_y(ui_Label107, 193);
    lv_obj_set_align(ui_Label107, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label107, "9");
    lv_obj_set_style_text_color(ui_Label107, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label107, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label107, &ui_font_B216, LV_PART_MAIN | LV_STATE_DEFAULT);

}
