// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen10_screen_init(void)
{
    ui_Screen10 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen10, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image24 = lv_img_create(ui_Screen10);
    lv_img_set_src(ui_Image24, &ui_img_18_png);
    lv_obj_set_width(ui_Image24, LV_SIZE_CONTENT);   /// 111
    lv_obj_set_height(ui_Image24, LV_SIZE_CONTENT);    /// 112
    lv_obj_set_x(ui_Image24, -169);
    lv_obj_set_y(ui_Image24, -157);
    lv_obj_set_align(ui_Image24, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image24, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image24, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image25 = lv_img_create(ui_Screen10);
    lv_img_set_src(ui_Image25, &ui_img_19_png);
    lv_obj_set_width(ui_Image25, LV_SIZE_CONTENT);   /// 111
    lv_obj_set_height(ui_Image25, LV_SIZE_CONTENT);    /// 112
    lv_obj_set_x(ui_Image25, -31);
    lv_obj_set_y(ui_Image25, -154);
    lv_obj_set_align(ui_Image25, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image25, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image25, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image26 = lv_img_create(ui_Screen10);
    lv_img_set_src(ui_Image26, &ui_img_20_png);
    lv_obj_set_width(ui_Image26, LV_SIZE_CONTENT);   /// 112
    lv_obj_set_height(ui_Image26, LV_SIZE_CONTENT);    /// 112
    lv_obj_set_x(ui_Image26, 136);
    lv_obj_set_y(ui_Image26, -152);
    lv_obj_set_align(ui_Image26, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image26, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image26, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image27 = lv_img_create(ui_Screen10);
    lv_img_set_src(ui_Image27, &ui_img_22_png);
    lv_obj_set_width(ui_Image27, LV_SIZE_CONTENT);   /// 144
    lv_obj_set_height(ui_Image27, LV_SIZE_CONTENT);    /// 115
    lv_obj_set_x(ui_Image27, -158);
    lv_obj_set_y(ui_Image27, 6);
    lv_obj_set_align(ui_Image27, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image27, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image27, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image28 = lv_img_create(ui_Screen10);
    lv_img_set_src(ui_Image28, &ui_img_23_png);
    lv_obj_set_width(ui_Image28, LV_SIZE_CONTENT);   /// 143
    lv_obj_set_height(ui_Image28, LV_SIZE_CONTENT);    /// 115
    lv_obj_set_x(ui_Image28, 5);
    lv_obj_set_y(ui_Image28, 4);
    lv_obj_set_align(ui_Image28, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image28, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image28, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image29 = lv_img_create(ui_Screen10);
    lv_img_set_src(ui_Image29, &ui_img_24_png);
    lv_obj_set_width(ui_Image29, LV_SIZE_CONTENT);   /// 135
    lv_obj_set_height(ui_Image29, LV_SIZE_CONTENT);    /// 114
    lv_obj_set_x(ui_Image29, 153);
    lv_obj_set_y(ui_Image29, 0);
    lv_obj_set_align(ui_Image29, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image29, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image29, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image30 = lv_img_create(ui_Screen10);
    lv_img_set_src(ui_Image30, &ui_img_25_png);
    lv_obj_set_width(ui_Image30, LV_SIZE_CONTENT);   /// 136
    lv_obj_set_height(ui_Image30, LV_SIZE_CONTENT);    /// 114
    lv_obj_set_x(ui_Image30, -146);
    lv_obj_set_y(ui_Image30, 155);
    lv_obj_set_align(ui_Image30, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image30, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image30, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image31 = lv_img_create(ui_Screen10);
    lv_img_set_src(ui_Image31, &ui_img_26_png);
    lv_obj_set_width(ui_Image31, LV_SIZE_CONTENT);   /// 128
    lv_obj_set_height(ui_Image31, LV_SIZE_CONTENT);    /// 105
    lv_obj_set_x(ui_Image31, 6);
    lv_obj_set_y(ui_Image31, 144);
    lv_obj_set_align(ui_Image31, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image31, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image31, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image32 = lv_img_create(ui_Screen10);
    lv_img_set_src(ui_Image32, &ui_img_27_png);
    lv_obj_set_width(ui_Image32, LV_SIZE_CONTENT);   /// 128
    lv_obj_set_height(ui_Image32, LV_SIZE_CONTENT);    /// 105
    lv_obj_set_x(ui_Image32, 154);
    lv_obj_set_y(ui_Image32, 145);
    lv_obj_set_align(ui_Image32, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image32, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image32, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}
