// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen5_screen_init(void)
{
    ui_Screen5 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image14 = lv_img_create(ui_Screen5);
    lv_img_set_src(ui_Image14, &ui_img_16_png);
    lv_obj_set_width(ui_Image14, LV_SIZE_CONTENT);   /// 14
    lv_obj_set_height(ui_Image14, LV_SIZE_CONTENT);    /// 65
    lv_obj_set_x(ui_Image14, -13);
    lv_obj_set_y(ui_Image14, 9);
    lv_obj_set_align(ui_Image14, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image14, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image15 = lv_img_create(ui_Screen5);
    lv_img_set_src(ui_Image15, &ui_img_1_png);
    lv_obj_set_width(ui_Image15, LV_SIZE_CONTENT);   /// 144
    lv_obj_set_height(ui_Image15, LV_SIZE_CONTENT);    /// 234
    lv_obj_set_x(ui_Image15, -124);
    lv_obj_set_y(ui_Image15, 11);
    lv_obj_set_align(ui_Image15, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image15, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image16 = lv_img_create(ui_Screen5);
    lv_img_set_src(ui_Image16, &ui_img_15_png);
    lv_obj_set_width(ui_Image16, LV_SIZE_CONTENT);   /// 148
    lv_obj_set_height(ui_Image16, LV_SIZE_CONTENT);    /// 115
    lv_obj_set_x(ui_Image16, 121);
    lv_obj_set_y(ui_Image16, 8);
    lv_obj_set_align(ui_Image16, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image16, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image17 = lv_img_create(ui_Screen5);
    lv_img_set_src(ui_Image17, &ui_img_9_png);
    lv_obj_set_width(ui_Image17, LV_SIZE_CONTENT);   /// 40
    lv_obj_set_height(ui_Image17, LV_SIZE_CONTENT);    /// 31
    lv_obj_set_x(ui_Image17, -11);
    lv_obj_set_y(ui_Image17, 226);
    lv_obj_set_align(ui_Image17, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image17, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label33 = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_Label33, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label33, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label33, -16);
    lv_obj_set_y(ui_Label33, -178);
    lv_obj_set_align(ui_Label33, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label33, "配网失败");
    lv_obj_set_style_text_font(ui_Label33, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label109 = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_Label109, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label109, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label109, -18);
    lv_obj_set_y(ui_Label109, -138);
    lv_obj_set_align(ui_Label109, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label109, "请重试");
    lv_obj_set_style_text_font(ui_Label109, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

}
