// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen9_screen_init(void)
{
    ui_Screen9 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen9, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image23 = lv_img_create(ui_Screen9);
    lv_img_set_src(ui_Image23, &ui_img_10_png);
    lv_obj_set_width(ui_Image23, LV_SIZE_CONTENT);   /// 480
    lv_obj_set_height(ui_Image23, LV_SIZE_CONTENT);    /// 159
    lv_obj_set_x(ui_Image23, 2);
    lv_obj_set_y(ui_Image23, 149);
    lv_obj_set_align(ui_Image23, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image23, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image23, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image21 = lv_img_create(ui_Screen9);
    lv_img_set_src(ui_Image21, &ui_img_45_png);
    lv_obj_set_width(ui_Image21, LV_SIZE_CONTENT);   /// 480
    lv_obj_set_height(ui_Image21, LV_SIZE_CONTENT);    /// 159
    lv_obj_set_align(ui_Image21, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image21, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image21, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image22 = lv_img_create(ui_Screen9);
    lv_img_set_src(ui_Image22, &ui_img_44_png);
    lv_obj_set_width(ui_Image22, LV_SIZE_CONTENT);   /// 480
    lv_obj_set_height(ui_Image22, LV_SIZE_CONTENT);    /// 159
    lv_obj_set_x(ui_Image22, -1);
    lv_obj_set_y(ui_Image22, -152);
    lv_obj_set_align(ui_Image22, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image22, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image22, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}
